(package "go-mode"
         "1.6.0"
         "Major mode for the Go programming language")

;; XXX: this is multiple-packages-in-on-repository
;;
;; Ignore this to get the package-lint to work
;;(package-file "go-mode.el")

(files "*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
